name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Login to Firebase
        uses: firebase/login-action@v1
        with:
          project_id: <your-project-id>
          token: ${{ secrets.FIREBASE_TOKEN }}
      
      - name: Build and deploy
        run: |
          npm run build
          firebase deploy --only hosting
